// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	client "guard_rails/client"

	mock "github.com/stretchr/testify/mock"

	scan "guard_rails/scan"
)

// RepositoryScanner is an autogenerated mock type for the RepositoryScanner type
type RepositoryScanner struct {
	mock.Mock
}

// Scan provides a mock function with given fields: file
func (_m *RepositoryScanner) Scan(file client.File) *scan.ScanResult {
	ret := _m.Called(file)

	var r0 *scan.ScanResult
	if rf, ok := ret.Get(0).(func(client.File) *scan.ScanResult); ok {
		r0 = rf(file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*scan.ScanResult)
		}
	}

	return r0
}

type mockConstructorTestingTNewRepositoryScanner interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositoryScanner creates a new instance of RepositoryScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositoryScanner(t mockConstructorTestingTNewRepositoryScanner) *RepositoryScanner {
	mock := &RepositoryScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
